version: 2.1

orbs:
  go: circleci/go@1.8.0

jobs:
  build:
    docker:
      - image: cimg/go:1.25
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - run:
          name: Build
          command: go build -o bin/server ./cmd/server

  test:
    docker:
      - image: cimg/go:1.25
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - run:
          name: Run tests
          command: go test -v ./...

  vet:
    docker:
      - image: cimg/go:1.25
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - run:
          name: Run vet
          command: go vet ./...

  format:
    docker:
      - image: cimg/go:1.25
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - run:
          name: Check formatting
          command: gofmt -l .

workflows:
  build-and-test-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - vet:
          requires:
            - build
      - format:
          requires:
            - build
